Models/Artist.cs
using System.ComponentModel.DataAnnotations;

namespace Art.Models
{
    public class Artist
    {
        public int ArtistId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Country { get; set; }
        public string ImageArtist { get; set; }
    }
}

Models/IArtistRepository.cs
using System.Collections.Generic;

namespace Art.Models
{
    public interface IArtistRepository
    {
        IEnumerable<Artist> AllArtist { get; }
       
    }
}

Models/IPaintingRepository.cs
using System.Collections.Generic;

namespace Art.Models
{
    public interface IPaintingRepository
    {
        IEnumerable<Painting> AllPainting { get; }
        Painting GetPainting(int PaintId);

    }
}

Models/MockArtistRepository.cs
using System.Collections.Generic;

namespace Art.Models
{
    public class MockArtistRepository : IArtistRepository
    {
        public IEnumerable<Artist> AllArtist => new List<Artist> { new Artist { ArtistId = 1, FirstName = "Sonja", LastName = "Brussen", Country = "Netherlands", Email = "Sonja@gmail.com", PhoneNumber = "0739888159" , ImageArtist = "https://dutch-accent.nl/wp-content/uploads/sonjabrussen.jpg" } };
    }
}

Models/MockPaintingRepository.cs
using System.Collections.Generic;
using System.Linq;

namespace Art.Models
{
    public class MockPaintingRepository : IPaintingRepository
    {
        private readonly IArtistRepository IArtistRepository = new MockArtistRepository();

        public IEnumerable<Painting> AllPainting =>new List<Painting> { new Painting { PainingId=1 ,PaintingName= "Silence of nature",PaintingType="Oil Painting" , Length = 140 , Width = 100 , DrawingYear= "2020", Image = "https://d3rf6j5nx5r04a.cloudfront.net/ygDxGa-_V-LBxFPO1SkGf0BS4zc=/1120x0/product/5/0/75fffbcf840b4b0ca7844ce74a92d220_opt.jpg", Price = 280 },
        new Painting{PainingId=2, PaintingName="Lucky", PaintingType="Oil Painting" , Length=52, Width=42 , DrawingYear = "2021", Image= "https://d3rf6j5nx5r04a.cloudfront.net/C775hrN-B1Rl1djwrujZr7N2ESs=/1120x0/product/9/8/324997ae1ef14461ba1ee7ba552b6938_opt.jpg" , Price = 93 },
        new Painting { PainingId = 3 , PaintingName="Behind the scene", PaintingType = "Oil painting" , Length=52, Width = 42, DrawingYear="2021" , Image="https://d3rf6j5nx5r04a.cloudfront.net/XilzqOuifRkv1zKLP09iWR0eCO4=/1120x0/product/9/8/bfd0972cc5c74aab8b09a4087cdb944b_opt.jpg", Price = 180 }  };

        public Painting GetPainting(int PaintId)
        {
            return AllPainting.FirstOrDefault(s => s.PainingId == PaintId);
        }
    }
}

Models/Painting.cs
using System.ComponentModel.DataAnnotations;

namespace Art.Models
{
    public class Painting
    {
        public int PainingId { get; set; }
        public string PaintingName { get; set; }
        public string PaintingType { get; set; }
        public int Length { get; set; }
        public int Width { get; set; }
        public string DrawingYear { get; set; }
        public string Image { get; set; }
        public decimal Price { get; set; }


    }
}

ViewModels/PaintingViewModel.cs
using System.Collections.Generic;
using Art.Models;

namespace Art.ViewModels
{
    public class PaintingViewModel
    {
        public IEnumerable<Painting> Paintings { get; set; }
        public string ArtistName { get; set; }
    }
}

Controllers/ArtistController.cs
using Art.Models;
using Microsoft.AspNetCore.Mvc;

namespace Art.Controllers
{
    public class ArtistController : Controller
    {
        private readonly IArtistRepository artistRepository;


        public ArtistController( IArtistRepository artistRepository)
        {
            this.artistRepository = artistRepository;
        }

        public IActionResult Artists()
        {
            return View(artistRepository.AllArtist);
        }
       
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Art.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/PaintingController.cs
using Microsoft.AspNetCore.Mvc;
using Art.Models;
using Art.ViewModels;

namespace Paintings.Controllers
{
    public class PaintingController : Controller
    {
        private readonly IPaintingRepository paintingRepository;
        private readonly IArtistRepository artistRepository;
      

        public PaintingController(IPaintingRepository paintingRepository, IArtistRepository artistRepository) 
        {
            this.paintingRepository = paintingRepository;
            this.artistRepository = artistRepository;   
        }

        public IActionResult AllPainting()
        {
            PaintingViewModel paintingViewModel = new PaintingViewModel();
            paintingViewModel.Paintings = paintingRepository.AllPainting;
            paintingViewModel.ArtistName = "Sonja Brussen";
            return View(paintingViewModel);
        }

    }
}

Views/Artist/Artists.cshtml
@model IEnumerable<Artist>

@{
    ViewData["Title"] = "Sonjas Contact Info";
}
    @foreach(var item in Model)
    {
        <div>
             <div class="container">
    <div class = "art-container">
        <div class="image-div-artist">
            <img class="image-artist" src="@item.ImageArtist" alt="Image"/>       
         </div>
        <div class="details-artist"> 
            <span><strong>Full Name :</strong> @item.FirstName @item.LastName</span>
            <span><strong>Country :</strong> @item.Country</span>
            <span><strong>Email :</strong> @item.Email</span>
            <span><strong>Phone Number :</strong> @item.PhoneNumber</span>   
        </div>
    </div>
</div>
    
        </div>
    }

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Sonjas Market";
}

<div class="select-container-main">
        <div class="select-container-sub">
        <div class="paintings">  
           @Html.ActionLink("Paintings","AllPainting","Painting",null, new { @class = "my-paintings" })   
        </div>
        <div class="contact">
             @Html.ActionLink("Contact","Artists","Artist",null, new { @class = "my-contact" })  
        </div>
    </div>
    
</div>

Views/Painting/AllPainting.cshtml
@model PaintingViewModel
@{
    ViewData["Title"] = "Sonjas Paintings";
}
    @foreach(var item in Model.Paintings)
    {
         <div class="container">
    <div class = "painting-container">
        <div class="image-div">
            <img class="image" src="@item.Image" alt="Image"/>       
         </div>
        <div class="details"> 
            <span class="artist-name"> @Model.ArtistName </span>
            <div class="details-des">
            <span><strong>Painting Number :</strong>  @item.PainingId</span>
            <span><strong>Subject :</strong> @item.PaintingName</span>
            <span><strong>Type :</strong> @item.PaintingType</span>
            <span><strong>Size :</strong> @item.Length x @item.Width CM </span>
            <span><strong>Drawing Year :</strong> @item.DrawingYear</span>
            <span><strong>Price :</strong> @item.Price $</span>
            </div>
            
        </div>
    </div>
           </div>
    
    }

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
     <link href="~/Content/Painting.css" rel="stylesheet" />
     <link href="~/Content/Artist.css" rel="stylesheet" />
     <link href="~/Content/site.css" rel="stylesheet" />
     <link href="~/Content/Index.css" rel="stylesheet" />


    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>